export interface Wine {
  id: string;
  prefix: string;
  name: string;
  appellation: string;
  subtitle: string;
  year: string;
  description: string;
  blend: string;
  surface: string;
  accent: string;
  image: string;
  category: "champagne" | "bordeaux" | "coteaux";
}

export const wines: Wine[] = [
  // ═══ BORDEAUX ═══
  {
    id: "gilette",
    prefix: "Château",
    name: "Gilette",
    appellation: "SAUTERNES",
    subtitle: "Crème de Tête",
    year: "1989",
    description: "Vieilli 20 ans en cuves béton avant mise en bouteille. Le plus vieux Sauternes commercialisé au monde. Seulement 5 000 bouteilles par millésime.",
    blend: "90% Sémillon · 8% Sauvignon · 2% Muscadelle",
    surface: "4,5 ha · Preignac",
    accent: "#D4A017",
    image: "/bottles/gilette.png",
    category: "bordeaux",
  },
  {
    id: "gilette-sauternes",
    prefix: "Château",
    name: "Gilette",
    appellation: "SAUTERNES",
    subtitle: "Sauternes",
    year: "2015",
    description: "Le second vin du Château Gilette. Même terroir, même exigence, un élevage plus court pour une expression fruitée et dorée du Sauternais.",
    blend: "80% Sémillon · 15% Sauvignon · 5% Muscadelle",
    surface: "4,5 ha · Preignac",
    accent: "#C9A020",
    image: "/bottles/gilette-sauternes.png",
    category: "bordeaux",
  },
  {
    id: "les-justices",
    prefix: "Château",
    name: "Les Justices",
    appellation: "SAUTERNES",
    subtitle: "Sauternes",
    year: "2019",
    description: "Un Sauternes de plaisir, élégant et accessible. Même terroir de Preignac, élevage en cuves pour préserver la fraîcheur du fruit.",
    blend: "85% Sémillon · 10% Sauvignon · 5% Muscadelle",
    surface: "8 ha · Preignac",
    accent: "#D4A017",
    image: "/bottles/les-justices.png",
    category: "bordeaux",
  },
  {
    id: "eyrins",
    prefix: "Château des",
    name: "Eyrins",
    appellation: "MARGAUX",
    subtitle: "Grand Vin de Bordeaux",
    year: "2022",
    description: "Micro-domaine de trois hectares cerné par les vignes du Premier Grand Cru Classé Château Margaux. Dense, profond, d'une finesse rare.",
    blend: "70% Cab. Sauv. · 27% Merlot · 3% Petit Verdot",
    surface: "2,9 ha · Margaux",
    accent: "#8B2635",
    image: "/bottles/eyrins.png",
    category: "bordeaux",
  },
  {
    id: "closerie-eyrins",
    prefix: "La Closerie des",
    name: "Eyrins",
    appellation: "MARGAUX",
    subtitle: "Margaux",
    year: "2017",
    description: "Second vin du Château des Eyrins. L'élégance margalaise dans une expression plus immédiate, soyeuse et gourmande.",
    blend: "65% Cab. Sauv. · 30% Merlot · 5% Petit Verdot",
    surface: "2,9 ha · Margaux",
    accent: "#8B2635",
    image: "/bottles/closerie-eyrins.png",
    category: "bordeaux",
  },
  {
    id: "respide",
    prefix: "Château",
    name: "Respide-Medeville",
    appellation: "GRAVES",
    subtitle: "Blanc",
    year: "2021",
    description: "Graves blanc d'exception. Notes de fleurs blanches, fruits à chair blanche, finale minérale ciselée — l'élégance bordelaise dans sa version la plus pure.",
    blend: "50% Sémillon · 48% Sauvignon · 2% Muscadelle",
    surface: "15 ha · Toulenne",
    accent: "#6B7F5E",
    image: "/bottles/respide.png",
    category: "bordeaux",
  },
  {
    id: "monplaisir",
    prefix: "Cru",
    name: "Monplaisir",
    appellation: "GRAVES",
    subtitle: "Grand Vin de Bordeaux",
    year: "2019",
    description: "Un Graves rouge structuré, élevé en fûts de chêne. Rondeur et profondeur sur un terroir de graves profondes.",
    blend: "60% Merlot · 40% Cab. Sauv.",
    surface: "5 ha · Toulenne",
    accent: "#5C3A3A",
    image: "/bottles/monplaisir.png",
    category: "bordeaux",
  },
  {
    id: "domaine-justices",
    prefix: "Domaine des",
    name: "Justices",
    appellation: "BORDEAUX SUPÉRIEUR",
    subtitle: "Bordeaux Supérieur",
    year: "2020",
    description: "Un Bordeaux Supérieur charnu et généreux, reflet du terroir familial de Preignac. Accessible et convivial.",
    blend: "70% Merlot · 30% Cab. Sauv.",
    surface: "6 ha · Preignac",
    accent: "#5C3A3A",
    image: "/bottles/domaine-justices.png",
    category: "bordeaux",
  },

  // ═══ CHAMPAGNE ═══
  {
    id: "champ-alouette",
    prefix: "Champagne",
    name: "Champ d'Alouette",
    appellation: "CHAMPAGNE GRAND CRU",
    subtitle: "Extra Brut · Le Mesnil-sur-Oger",
    year: "2008",
    description: "Pur Chardonnay du Mesnil-sur-Oger, Grand Cru. Quatorze ans sur lattes, dosage extra-brut. La pureté cristalline de la craie champenoise.",
    blend: "100% Chardonnay · Grand Cru",
    surface: "12 ha · 8 villages",
    accent: "#C9A96E",
    image: "/bottles/champ-alouette.png",
    category: "champagne",
  },
  {
    id: "grande-ruelle",
    prefix: "Champagne",
    name: "La Grande Ruelle",
    appellation: "CHAMPAGNE GRAND CRU",
    subtitle: "Extra Brut · Ambonnay",
    year: "2007",
    description: "Grand Cru d'Ambonnay. Pinot Noir de terroir, puissant et vineux. Un champagne de gastronomie à la structure affirmée.",
    blend: "100% Pinot Noir · Grand Cru",
    surface: "12 ha · Ambonnay",
    accent: "#B8860B",
    image: "/bottles/grande-ruelle.png",
    category: "champagne",
  },
  {
    id: "theophile",
    prefix: "Champagne",
    name: "Cuvée Théophile",
    appellation: "CHAMPAGNE GRAND CRU",
    subtitle: "Extra Brut",
    year: "2009",
    description: "Hommage au fondateur. Assemblage Grand Cru de Chardonnay et Pinot Noir, élevé longuement sur lattes. Complexité et profondeur.",
    blend: "50% Chardonnay · 50% Pinot Noir · Grand Cru",
    surface: "12 ha · Le Mesnil / Ambonnay",
    accent: "#C9A96E",
    image: "/bottles/theophile.png",
    category: "champagne",
  },
  {
    id: "blanc-de-noirs",
    prefix: "Champagne",
    name: "Blanc de Noirs",
    appellation: "CHAMPAGNE PREMIER CRU",
    subtitle: "Brut",
    year: "NV",
    description: "100% Pinot Noir de Premier Cru. Vineux, fruité, avec une belle matière. Le champagne de table par excellence.",
    blend: "100% Pinot Noir · Premier Cru",
    surface: "12 ha · Bisseuil",
    accent: "#C9A96E",
    image: "/bottles/blanc-de-noirs.png",
    category: "champagne",
  },
  {
    id: "rose",
    prefix: "Champagne",
    name: "Rosé",
    appellation: "CHAMPAGNE PREMIER CRU",
    subtitle: "Extra Brut",
    year: "NV",
    description: "Rosé de saignée, couleur saumon pâle. Frais, délicat, avec des notes de petits fruits rouges. Élégance et légèreté.",
    blend: "100% Pinot Noir · Premier Cru",
    surface: "12 ha · Bisseuil",
    accent: "#D4918B",
    image: "/bottles/rose.png",
    category: "champagne",
  },

  // ═══ COTEAUX CHAMPENOIS ═══
  {
    id: "athenais",
    prefix: "Cuvée",
    name: "Athénaïs",
    appellation: "COTEAUX CHAMPENOIS",
    subtitle: "Rouge · Ambonnay",
    year: "2019",
    description: "Vin tranquille rouge, pas un champagne. Pinot Noir d'Ambonnay Grand Cru vinifié comme un grand bourgogne. Rare et confidentiel.",
    blend: "100% Pinot Noir · Grand Cru",
    surface: "0,5 ha · Ambonnay",
    accent: "#722F37",
    image: "/bottles/athenais.png",
    category: "coteaux",
  },
];
